# -*- coding: utf-8 -*-
"""P2_RestrepoLeon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rDwjZYRoQga5MobgZdi9VF7Gos7lt9v6
"""

from ast import Return
import random
from scipy.integrate import quad


repeticiones = 50000
a = 0
b = 4
c = 5
listaPuntos = []
NumAciertos = 0
nivelConfianzaDeseado = 0.95
def evaluarFuncion(x):
    funcion = (x + (x + (x)**(1/2))**(1/2))**(1/2)
    return funcion


def CalcularXi(a, b):
    U = random.uniform(0, 1)
    Xi = a + U * (b - a)
    return Xi

for i in range(repeticiones):
    X = CalcularXi(a, b)
    Y = CalcularXi(0, c)
    listaPuntos.append([X, Y])
    x = listaPuntos[i][0]
    y = listaPuntos[i][1]
    if evaluarFuncion(x) >= CalcularXi(a, b):
      NumAciertos+=1

pGorro = (NumAciertos/repeticiones)


#Estimar el valor de I=∫40(x+(x+(x)1/2)1/2))1/2 con a = 0 y b = 4
#usando el método de acierto/falla y calcular un intervalo de confianza para esta estimación.

IntegAciertoFallo = c * (b - a) * (N_H / NXD)

Ireal, error = quad(evaluarFuncion, a, b)

Z = 1.96
Theta = Z*(( (pGorro*(1-pGorro))**(1/2)) * ((b-a)*c) / (repeticiones**1/2))



print(f"Valor real de la integral I  = {Ireal}")
print(f"Valor de I con la integral de montecarlo metodo Acierto Fallo = {IntegAciertoFallo}")
print(f"El intervalo de confianza es {IntegAciertoFallo} +- {Theta}")

#metodo de la media muestral
#Estimar el valor de I=∫40(x+(x+(x)1/2)1/2))1/2 con a = 0 y b = 4

PuntosMetodoMediaMuestral = []

for i in range(repeticiones):
    X = CalcularXi(a, b)
    Y = CalcularXi(0, c)
    PuntosMetodoMediaMuestral.append([X, Y])

GXi = []
for i in range(repeticiones):
    x = listaPuntos[i][0]
    GXi.append(evaluarFuncion(x))

IntegMediaMuestral = ((b-a)*(1/NXD))*sum(GXi)

print(f"Valor encontrado de I con la integral de montecarlo metodo de media muestral = {IntegMediaMuestral}")

#Comparar ambos valores

DiferenciaIAleatoria = abs(Ireal- IntegAciertoFallo)
DiferenciaIMuestral = abs(Ireal - IntegMediaMuestral)

Menor = min(DiferenciaIAleatoria, DiferenciaIMuestral)

if Menor == DiferenciaIMuestral:
  print("\n En esta prueba es mas cercana por el método de la media muestral.")
elif Menor == DiferenciaIAleatoria:
  print("\n En esta prueba es mas cercana por el método de acierto/fallo.")